// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int total = Integer.parseInt(args[0]);
	int timeless = 0;
	int timesmore = 0;
	double count;
	while (total >0){
		count = Math.random();
		if (count <= 0.5) {
			timeless = timeless + 1;
		} else{
			timesmore = timesmore + 1;
		}
		count = 0;
		total = total - 1;
	}
	if (timesmore == 0 || timeless == 0 ) {
		System.out.println("> 0.5:" + timesmore + "times" );
		System.out.println("<= 0.5:" + timeless + "times");
		return;
	}
	double ratio = ((double)(Math.min(timeless, timesmore)) / (double)(Math.max(timeless, timesmore)));
	System.out.println("> 0.5:" + timesmore + "times" );
	System.out.println("<= 0.5:" + timeless + "times");
	System.out.println("ratio: " + ratio);
	}
}
